language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6.9.2'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
# script: ./node_modules/.bin/karma start karma.conf.js --browser Firefox --single-run
script: npm run test
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
